---
special_routes:
  - content_id: "b6bb372b-3c4e-4a21-98a6-ffbf2ea5dc9e"
    base_path: "/sign-in"
    title: "Sign in to GOV.UK"
    rendering_app: "frontend"
  - content_id: "f04c45a7-c20b-4f66-a485-dc997a6a3b6d"
    base_path: "/sign-in/callback"
    title: "Sign in to GOV.UK (OAuth Callback)"
    rendering_app: "frontend"
  - content_id: "7ee16fff-900d-4f5d-bd0a-62fdaa1ad3b6"
    base_path: "/sign-out"
    title: "Sign out from GOV.UK"
    rendering_app: "frontend"
  - content_id: "c1f08359-21f7-49c1-8811-54bf6690b6a3"
    base_path: "/account/home"
    title: "Account home page"
    rendering_app: "frontend"
  - content_id: "e5098fc2-ad79-4c6f-882b-410831c12f60"
    base_path: "/account/saved-pages/add"
    title: "Save a page"
    rendering_app: "frontend"
  - content_id: "3aeaeb46-b3c5-449b-8a3b-2753ffef3c9f"
    base_path: "/account/saved-pages/remove"
    title: "Remove a saved page"
    rendering_app: "frontend"
