---
help_pages:
  sign_in:
    content_id: "b6bb372b-3c4e-4a21-98a6-ffbf2ea5dc9e"
    base_path: "/sign-in"
    title: "Sign in to a service"
    description: "Find the government service you need to sign in to. At the moment, there are separate accounts for different government services."
    rendering_app: "frontend"

special_routes:
  - content_id: "49ecdc1f-c98b-430e-8256-7a402239daf8"
    base_path: "/sign-in/redirect"
    title: "Sign in to GOV.UK (OAuth Redirect)"
    rendering_app: "frontend"
  - content_id: "f04c45a7-c20b-4f66-a485-dc997a6a3b6d"
    base_path: "/sign-in/callback"
    title: "Sign in to GOV.UK (OAuth Callback)"
    rendering_app: "frontend"
  - content_id: "ff675fc1-2f0b-4f07-8dd3-bfe24d4318f8"
    base_path: "/sign-in/first-time"
    title: "Control how we use information about you"
    rendering_app: "frontend"
  - content_id: "7ee16fff-900d-4f5d-bd0a-62fdaa1ad3b6"
    base_path: "/sign-out"
    title: "Sign out from GOV.UK"
    rendering_app: "frontend"
  - content_id: "c1f08359-21f7-49c1-8811-54bf6690b6a3"
    base_path: "/account/home"
    title: "Account home page"
    rendering_app: "frontend"
  - content_id: "19c4cef8-d0ad-483b-93ea-e07f7ed4734a"
    base_path: "/account/cookies-and-feedback"
    title: "Cookie and feedback settings"
    rendering_app: "frontend"
  - content_id: "f8f91a56-2298-4365-9590-d7e80fe8c066"
    base_path: "/api/personalisation/check-email-subscription"
    title: "Account API - Check email Subscription"
    description: "Personalisation API exposing email subscription data for progressive enhancement of GOV.UK pages"
    rendering_app: "account-api"
