test:
  session_secret: secret
  oauth_provider_url: http://openid-provider
  oauth_client_id: client-id
  oauth_client_secret: client-secret
  oauth_client_private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDctOcm72vb2bPM
    PtYUJGCtxZMQL/7uRykyRsdomvrK2f2Tf5x9X1y3bWwsSDeQqe5we9SZ3Zc2YLhc
    v/yC6UOYsuH0Mocz879eIi4XIme0mrzV32GHiFnyTstfZmakzoMKWvRZzOxofYPJ
    92WMRkdkfj5tan4HQeXv3h8mMNPerW9tM893EB/iUihOg4d48OWEvl9mhDP9JbMd
    zBrv+qn5vQ1KnsuqrC7Gw8mZmhNYvH1esXKSHlmRU3IR8Ga5KHnm8IXGLrITJLUf
    C+l0iPTzckAH6gtQkdHsKSFcR4O3aDbnKwM6pDS2tCQ0wE/m/O7DFEas97mBIu6/
    NiAGfnm7AgMBAAECggEBALcMpwaI3mkqJ1BH8WAlR7X4Pt/XHtXbWVSklXCx0T17
    DTBPT6g/9nL/ow8bGlK2TdcnLQ4sVeS41U+/v5uIAhNckcDqQ26YQ+i76oQvedm1
    2NZ9fbNeKFOqfEx0br9TtCVbiHwOVSjYqPxSXvu3sjCr7/TptPsp8Z4/GJChQKfW
    n91T+SAKfqIoIr5UrkFZyV7tOPIqh+EdXZJ1NsUTnOU6nkjc3jEeUsh4u4VHItjZ
    fqgPe7E1qNErw66OWlqySGc+i4zkH9XgaMssH75eK4kIHk49qeH/BYhBmEX0kH+k
    bWCPDdZIOVXfSTLY8bDK2PjheWXqDDss4kGy1jUnKDECgYEA+h9puYbWEl1zfs2D
    6lOwlMjVWMIYmk00Pl1K48tvBUap63Wphj5W3KWNICeEwvxF6k/68X9iiRY9Clmg
    KhNKUHSBYr8GMrlKXit96MXtrNiUdIVrZK34j7tg3g+c1ysiuM2atCqPHHhEecu8
    YxPdiKqPTo3kX699aRr45pQsTgkCgYEA4eSKblAGg+akIlmTXcLb6xf5ZdICO6Ou
    txve6SDtM6uX2yLFt18iUbAf5kqNDgKIdun3cGbqIVWZgw8Izw+BUUx1nR4T13da
    kdNZgM8rnjQVjDfSQ1X2K6rGPDVrhLnNHYHQB8AfzBAR+UUmUqHr+U5OxI1cxCVV
    hkBHRB50+qMCgYEAgSSjBAXYlhbmQTx/tgeMDuY7Md7VsSXXqbOlrUQmiITZyxcv
    dn7NfpOD8Gw3Ii37M2YkXXi2Oa3fym5IQjE/l5bwDzouSxZcjY7LLdq0QyB4Vkll
    D9C7nArVkxJgmsBM5zpRfGDVD5ARWwmUtVtWcPAPmjGtDrKfgBtLFFLBJXECgYEA
    kLebwCRgqCwgxyjf8leeELUhQAwVBiRNEF44pt5DWLD77pYOWPYHxJGzPhRQ3cLd
    rmEh9s7X/FccrAv7trvWO0FisC/OwmFikr32P0F6TjZL/7Lbb+woc71KltQad8OZ
    FuhNYEnDlTZObYXRkWrPBL8YU2/FGJxaeFHB1nA0vUUCgYBg9h0biOJvTPA8MlOn
    Q+AooozARsyAVqjQY72iNJvUZ7gLq1IJafYazVHwEpDTGgVlvrFx0lGiomsBTWJq
    JAJLCTv63UqXk1XQhLWs+cryzJOF0OKrRoVXirscX9QSATrzwDJIEtlCeojADDdN
    /Tujell5EhSlXzKcxz9m684wzg==
    -----END PRIVATE KEY-----

development:
  session_secret: secret
  oauth_provider_url: <%= ENV.fetch('GOVUK_ACCOUNT_OAUTH_PROVIDER_URI', 'http://openid-provider') %>
  oauth_client_id: <%= ENV.fetch('GOVUK_ACCOUNT_OAUTH_CLIENT_ID', 'client-id') %>
  oauth_client_secret: <%= ENV.fetch('GOVUK_ACCOUNT_OAUTH_CLIENT_SECRET', 'client-secret') %>
  oauth_client_private_key: |
<%= ENV["GOVUK_ACCOUNT_OAUTH_PRIVATE_KEY"]&.gsub(/^/, '    \1') %>

production:
  session_secret: <%= ENV.fetch('SESSION_SECRET', ENV['SESSION_SIGNING_KEY']) %>
  oauth_provider_url: <%= ENV['GOVUK_ACCOUNT_OAUTH_PROVIDER_URI'] %>
  oauth_client_id: <%= ENV['GOVUK_ACCOUNT_OAUTH_CLIENT_ID'] %>
  oauth_client_secret: <%= ENV['GOVUK_ACCOUNT_OAUTH_CLIENT_SECRET'] %>
  oauth_client_private_key: |
<%= ENV["GOVUK_ACCOUNT_OAUTH_PRIVATE_KEY"]&.gsub(/^/, '    \1') %>
