test:
  session_signing_key: secret
  govuk_notify_api_key: govuk-notify-api-key
  govuk_notify_template_id: govuk-notify-template-id
  oauth_client_id: client-id
  oauth_client_secret: client-secret

development:
  session_signing_key: secret
  govuk_notify_api_key: govuk-notify-api-key
  govuk_notify_template_id: govuk-notify-template-id
  oauth_client_id: <%= ENV.fetch('GOVUK_ACCOUNT_OAUTH_CLIENT_ID', 'client-id') %>
  oauth_client_secret: <%= ENV.fetch('GOVUK_ACCOUNT_OAUTH_CLIENT_SECRET', 'client-secret') %>

production:
  session_signing_key: <%= ENV['SESSION_SIGNING_KEY'] %>
  govuk_notify_api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>
  govuk_notify_template_id: <%= ENV['GOVUK_NOTIFY_TEMPLATE_ID'] %>
  oauth_client_id: <%= ENV['GOVUK_ACCOUNT_OAUTH_CLIENT_ID'] %>
  oauth_client_secret: <%= ENV['GOVUK_ACCOUNT_OAUTH_CLIENT_SECRET'] %>
