---
:concurrency: 2
<% if ENV.key?('SIDEKIQ_LOGFILE') %>
:logfile: <%= ENV['SIDEKIQ_LOGFILE'] %>
<% end %>


:queues:
  - default

:schedule:
  expired_auth_request_worker:
    every: '1h'
    class: ExpiredAuthRequestWorker

  expired_sensitive_exception_worker:
    every: '1h'
    class: ExpiredSensitiveExceptionWorker

  expired_tombstone_worker:
    every: '1h'
    class: ExpiredTombstoneWorker
