---
:concurrency: 2
:logfile: ./log/sidekiq.json.log

:queues:
  - default

:schedule:
  expired_auth_request_worker:
    every: '1h'
    class: ExpiredAuthRequestWorker

  expired_sensitive_exception_worker:
    every: '1h'
    class: ExpiredSensitiveExceptionWorker

  expired_tombstone_worker:
    every: '1h'
    class: ExpiredTombstoneWorker
