---
:concurrency: 2

:queues:
  - default
:scheduler:
  :schedule:
    expired_auth_request_job:
      every: '1h'
      class: ExpiredAuthRequestJob

    expired_sensitive_exception_job:
      every: '1h'
      class: ExpiredSensitiveExceptionJob

    expired_tombstone_job:
      every: '1h'
      class: ExpiredTombstoneJob
