shared:
  email:
    type: cached
    writable: false

  email_verified:
    type: cached
    writable: false

  # TODO: remove this attribute after removing its use from other apps
  has_unconfirmed_email:
    type: cached
    writable: false

  cookie_consent:
    type: local

  feedback_consent:
    type: local

  transition_checker_state:
    type: local
    get_requires_mfa: true
    set_requires_mfa: true
