---
email:
  type: cached
  writable: false
  permissions:
    check: 0
    get: 0

email_verified:
  type: cached
  writable: false
  permissions:
    check: 0
    get: 0

has_unconfirmed_email:
  type: cached
  writable: false
  permissions:
    check: 0
    get: 0

transition_checker_state:
  type: local
  permissions:
    check: 0
    get: 1
    set: 1
